"""empty message

Revision ID: 23ed9fe32079
Revises: eae0d5a6c0a7
Create Date: 2019-06-28 19:55:12.365647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23ed9fe32079'
down_revision = 'eae0d5a6c0a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('birthday', table_name='person')
    op.drop_index('gender', table_name='person')
    op.drop_index('password', table_name='person')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('password', 'person', ['password'], unique=True)
    op.create_index('gender', 'person', ['gender'], unique=True)
    op.create_index('birthday', 'person', ['birthday'], unique=True)
    # ### end Alembic commands ###
